#!/bin/sh

# Change to always run from the root of the repo.
cd "$(git rev-parse --show-toplevel)" || exit

golangci-lint run --fix ./...

# Capture the exit code of golangci-lint and check if there were any linting errors.
if [ $? -ne 0 ]; then
    echo "Linting failed. Please fix the issues before committing."
    exit 1
fi

exit 0
